app/Http/routes.php
<?php

Route::get('/','FrontController@index');
Route::get('admin','FrontController@admin');
Route::get('whatsapp','FrontController@whatsapp');
Route::get('estados-financieros/{year?}','FrontController@getEstadosFinancieros');
Route::get('subir_estados-financieros','FrontController@uploadEstadosFinancieros');
Route::post('upload_file' , 'FrontController@upload_file');

Route::resource('posts','PostController');
Route::resource('users','UsersController');
Route::resource('reviews','ReviewsController');

Route::resource('mail','MailController');
Route::resource('log','LogController');
Route::get('login','LogController@index');
Route::get('logout','LogController@logout');

Route::resource('firstmenu','FirstMenuController');
Route::resource('secondmenu','SecondMenuController');
Route::resource('thirdmenu','ThirdMenuController');

Route::get('secondsmenus/{id}',      'FirstMenuController@getSecondsMenus');
Route::get('thirdsmenus/{id}',        'SecondMenuController@getThirdsMenus');

Route::get('frecuencia-recomendada/{slug}',   'PostController@show');
Route::get('enfermedades-visuales/{slug}',    'PostController@show');
Route::get('enfermedades-sistemicas/{slug}',  'PostController@show');
Route::get('articulos/{slug}',                'PostController@show');
Route::get('examenes/{slug}',                 'PostController@show');
Route::get('cirugias-y-tratamientos/{slug}',  'PostController@show');
Route::get('prevencion/{slug}',               'PostController@show');
Route::get('nuestra-clinica/{slug}',          'PostController@show');
Route::get('autoComplete',                    'PostController@autoComplete');

// RUTAS MANUALES
Route::get('{slug}',  'PostController@show');

app/Post.php
<?php

namespace altavisionApp;
use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
  use Sluggable;
  public function sluggable()
  {
      return [
          'slug' => [
              'source' => 'title'
          ]
      ];
  }
  protected $table = 'posts';
  protected $fillable = ['first_menu_id','second_menu_id','third_menu_id','title','slug','content'];

    public function firstMenu()
    {
      return $this->belongsTo('altavisionApp\FirstMenu');
    }
    public function secondMenu()
    {
      return $this->belongsTo('altavisionApp\SecondMenu');
    }
    public function thirdMenu()
    {
      return $this->belongsTo('altavisionApp\ThirdMenu');
    }
    public function scopeTitle($query , $name)
    {
        return $query->where('title','LIKE','%'.$name.'%');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace altavisionApp\Http\Controllers;

use Illuminate\Http\Request;
use altavisionApp\FirstMenu;
use altavisionApp\SecondMenu;
use altavisionApp\ThirdMenu;
use altavisionApp\Post;
use altavisionApp\Http\Requests;
use altavisionApp\Http\Controllers\Controller;

class PostController extends Controller
{
    public function __construct(){
      $this->middleware('auth', ['only' => ['index', 'create' , 'store', 'edit', 'update', 'destroy']]);
    }
////////////////////////////////////////////////////////
    public function index(Request $request)
    {
      $posts=Post::
      title($request->name)->
      orderBy('created_at')->get();
      return view('posts.index', ['posts'=>$posts]);
    }
/////////////////////////////////////////////////////////
    public function create()
    {
      $firstlist=FirstMenu::lists('name','id');
      return view('posts.create', ['firstlist'=>$firstlist]);
    }
/////////////////////////////////////////////////////////
    public function store(Request $request)
    {
      Post::create($request->all());
      Flash('Post creado satisfactoriamente' , 'success');
      return Redirect('posts');
      // return $request->all();
    }
/////////////////////////////////////////////////////////
    public function show($slug , Request $request)
    {
      $post =        Post::
      where('slug','=', $slug)
      ->firstOrFail();

      if (!isset($request->title)) {
        $firstPosts = Post::
          where('first_menu_id', '=', $post->first_menu_id)
          ->whereNull('second_menu_id')
          ->get();
      }elseif(isset($request->title)){
        $firstPosts=Post::
        title($request->title)->
        orderBy('created_at')->get();
      }

      $secondPosts = Post::
        where('first_menu_id', '=', $post->first_menu_id)
        ->whereNotNull('second_menu_id')
        ->get();

      $secondMenus = SecondMenu::where('first_menu_id','=', $post->first_menu_id)->get();
      // return dd($secondMenus);
      $thirdMenus  = ThirdMenu::where('id','=', $post->third_menu_id)->get();
      return view('posts.view' , ['post'=>$post , 'firstPosts'=>$firstPosts , 'secondPosts'=>$secondPosts , 'thirdMenus'=>$thirdMenus , 'secondMenus'=>$secondMenus]);
    }
/////////////////////////////////////////////////////////
    public function edit($id)
    {
      $post=Post::find($id);
      $firstlist=FirstMenu::lists('name','id');
      $secondlist=SecondMenu::lists('name','id');
      $thirdlist=ThirdMenu::lists('name','id');
      return view('posts.edit', ['post'=>$post , 'firstlist'=>$firstlist , 'secondlist'=>$secondlist,'thirdlist'=>$thirdlist]);
    }
/////////////////////////////////////////////////////////
    public function update(Request $request, $id)
    {
      $post=Post::find($id);
      $post->first_menu_id    =$request->first_menu_id;
      $post->second_menu_id   =$request->second_menu_id;
      $post->third_menu_id    =$request->third_menu_id;
      $post->title            =$request->title;
      $post->content          =$request->content;
      $post->save();
      flash('Post actualizado satisfactoriamente', 'success');
      return Redirect('posts');
    }
/////////////////////////////////////////////////////////
    public function destroy($id)
    {
      Post::destroy($id);
      Flash('Post eliminado satisfactoriamente' , 'success');
      return redirect('posts');
    }
////////////////////////////////////////////////////////
    public function autoComplete(Request $request) {
      $query = $request->get('term','');
      $allPosts=Post::where('title','LIKE','%'.$query.'%')->get();
      $data=array();
      foreach ($allPosts as $post) {
        $data[]=array('menu'=>$post->firstMenu->slug , 'post'=> $post->slug, 'value'=>$post->title,'id'=>$post->id);
      }
      if(count($data))
        return $data;
      else
        return ['value'=>'No se han encontrado resultados','id'=>''];
    }
}

resources/views/posts/create.blade.php
@extends('layouts.dashboard')
@section('section')
  {!!Form::open(['route'=>'posts.store' , 'method'=>'POST' , 'class'=>'formulario'])!!}
    @include('posts.forms.create')
    <div class="form-group text-right">
      {!!Form::submit('Guardar' , ['class'=>'btn btn-success'])!!}
    </div>
  {!!Form::close()!!}
  {!!Html::script('plugins/ckeditor/ckeditor.js')!!}
  {!!Html::script('plugins/ckfinder/ckfinder.js')!!}
  <script>
    CKEDITOR.replace( 'txa',
    {
      filebrowserBrowseUrl        : '../plugins/ckfinder/ckfinder.html',
      filebrowserImageBrowseUrl   : '../plugins/ckfinder/ckfinder.html?type=Images',
      filebrowserUploadUrl        : '../plugins/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files',
      filebrowserImageUploadUrl   : '../plugins/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images'
    });
  </script>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.dashboard')
@section('section')
  {!!Form::model($post ,['route'=>['posts.update', $post->id] , 'method'=>'PUT' , 'class'=>'formulario'])!!}
    @include('posts.forms.edit')
    <div class="form-group text-right">
      {!!Form::submit('Guardar cambios' , ['class'=>'btn btn-success'])!!}
    </div>
  {!!Form::close()!!}
  {!!Html::script('plugins/ckeditor/ckeditor.js')!!}
  {!!Html::script('plugins/ckfinder/ckfinder.js')!!}
  <script>
    CKEDITOR.replace( 'txa',
    {
      filebrowserBrowseUrl        : '../../plugins/ckfinder/ckfinder.html',
      filebrowserImageBrowseUrl   : '../../plugins/ckfinder/ckfinder.html?type=Images',
      filebrowserUploadUrl        : '../../plugins/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files',
      filebrowserImageUploadUrl   : '../../plugins/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images'
    });
  </script>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.dashboard')
@section('section')
  {!!Form::open([ 'route'=>'posts.index' , 'method'=>'GET', 'class'=>'navbar-form'])!!}
    <div class="input-group">
      {!!Form::text('name' , null , ['class'=>'form-control' , 'placeholder'=>'Buscar aquí ...' , 'aria-describedby'=> 'search'])!!}
      <span class="input-group-addon" id="search"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></span>
    </div>
  {!!Form::close()!!}
  <table class="table">
    <thead>
      <th>Título</th>
      <th>Menu</th>
      <th>Acciones</th>
    </thead>
    @foreach ($posts as $post)
      <tbody>
        <td>{{$post->title}}</td>
        <td>{{$post->firstmenu->name}}</td>
        <td>
          {!!Form::open(['route'=>['posts.destroy',$post->id], 'method'=>'DELETE'])!!}
            <div class="form-group">
              <a href="{{ route('posts.show', $post->slug) }}"><i class="btn btn-success glyphicon glyphicon-eye-open"></i></a>
              <a href="{{ route('posts.edit', $post->id) }}"><i class="btn btn-primary glyphicon glyphicon-pencil"></i></a>
              {!! Form::button('<span class="glyphicon glyphicon-trash"></span>',
                [
                    'type' => 'button',
                    'class'=>'btn btn-danger',
                    'onclick' => 'if(confirm("¿Realmente desea eliminar este elemento? ")) {  $(form).submit(); }',
                ]) !!}
            </div>
          {!!Form::close()!!}
        </td>
      </tbody>
    @endforeach
  </table>
@endsection

resources/views/posts/view.blade.php
@extends('layouts.post')
@section('section')
    <aside class="col-xs-12 col-sm-3">
      {{-- SCRIPT  --}}
        @section('autocomplete')
        <script type="text/javascript">
          $(document).ready(function(){
            src = "../autoComplete";
            $("#search").autocomplete({
              source: function(request, response) {
                  $.ajax({
                     url: src,
                     dataType: "json",
                     data: {term : request.term},
                     success: function(data){
                         response(data);
                     }
                  });
               }, min_length: 3,
               select: function( event, ui ) {
                  $('#search').val(ui.item.value);
                  location.href='/'+ui.item.menu+'/'+ui.item.post;
                  return false;
              }
            });
          });
        </script>
        @endsection
      {{-- SEARCH FORM --}}
      {!!Form::open(['method'=>'GET', 'class'=>'navbar-form' , 'id'=>'form_search'])!!}
        <div class="row">
          <div class="col-xs-9">
            {!!Form::text('title' , null , ['id'=>'search' ,'class'=>'form-control' , 'placeholder'=>'Buscar aquí ...' , 'aria-describedby'=> 'search'])!!}
          </div>
          <div class="col-xs-3">
            {!! Form::button('<span class="glyphicon glyphicon-search"></span>', ['id'=>'btn_search','type' => 'submit', 'class'=>' form-control btn btn-primary']) !!}
          </div>
        </div>

      {!!Form::close()!!}
      {{-- FIRSTS MENU --}}
      <div class="list-group">
        @if (count($firstPosts)>0)
            @foreach ($firstPosts as $firstposts)
              <a href="{{ URL::to($firstposts->firstMenu->slug, $firstposts->slug) }}" class="list-group-item"
                @if (isset($_GET['title']))
                  id="mi_result"
              @endif>{{$firstposts->title}}</a>
            @endforeach
        @elseif (isset($_GET['title']))
          <a href="{{ URL::to($post->firstMenu->slug, $post->slug) }}" class="list-group-item" id="mi_result">Sin resultados. Regresar</a>
        @endif
      </div>
      {{-- SECONDS MENUS --}}
      @if (isset($secondMenus ) && empty($_GET['title']))
        <ul class="nav" id="side-menu">
          @foreach ($secondMenus as $menu)
            <li>
              <a href="#"><i class="">{!!$menu->name!!}</i><span class="fa arrow"></span></a>
              <ul class="nav nav-second-level">
                @foreach ($secondPosts as $poste)
                  @if ($menu->id == $poste->second_menu_id )
                    <li>
                      @if ($poste->id != $post->id)
                        <a  href="{{ URL::to($poste->firstMenu->slug, $poste->slug) }}" ><i class=''></i> {!!$poste->title!!}</a>
                      @else
                        <span class="active">{!!$poste->title!!}</span>
                      @endif
                    </li>
                  @endif
                @endforeach
              </ul>
            </li>
          @endforeach
        </ul>
      @endif
    </aside>
    {{-- CONTENIDO --}}
    <article class="col-xs-12 col-sm-9" id="mainContent">
      <h1>{!!$post->title!!}</h1>
      <div id="post_content">
        {!!$post->content!!}
      </div>
    </article>
    {{-- BOTON --}}
    @if ($post->firstMenu->slug == 'enfermedades-visuales' && empty($post->secondMenu->slug))
      <div class="pull-right">
        <?php
        $enfermedad=str_replace("-","",$post->slug);
        $path= 'http://www.'. $enfermedad . '.com.co';
        ?>
        <a href="{{$path}}" class="btn btn-success" target="_blank">Hablemos de {{$post->title}}</a>
      </div>
    @endif
@endsection