app/Http/routes.php
<?php

Route::get('/','FrontController@index');
Route::get('admin','FrontController@admin');
Route::get('whatsapp','FrontController@whatsapp');
Route::get('estados-financieros/{year?}','FrontController@getEstadosFinancieros');
Route::get('subir_estados-financieros','FrontController@uploadEstadosFinancieros');
Route::post('upload_file' , 'FrontController@upload_file');

Route::resource('posts','PostController');
Route::resource('users','UsersController');
Route::resource('reviews','ReviewsController');

Route::resource('mail','MailController');
Route::resource('log','LogController');
Route::get('login','LogController@index');
Route::get('logout','LogController@logout');

Route::resource('firstmenu','FirstMenuController');
Route::resource('secondmenu','SecondMenuController');
Route::resource('thirdmenu','ThirdMenuController');

Route::get('secondsmenus/{id}',      'FirstMenuController@getSecondsMenus');
Route::get('thirdsmenus/{id}',        'SecondMenuController@getThirdsMenus');

Route::get('frecuencia-recomendada/{slug}',   'PostController@show');
Route::get('enfermedades-visuales/{slug}',    'PostController@show');
Route::get('enfermedades-sistemicas/{slug}',  'PostController@show');
Route::get('articulos/{slug}',                'PostController@show');
Route::get('examenes/{slug}',                 'PostController@show');
Route::get('cirugias-y-tratamientos/{slug}',  'PostController@show');
Route::get('prevencion/{slug}',               'PostController@show');
Route::get('nuestra-clinica/{slug}',          'PostController@show');
Route::get('autoComplete',                    'PostController@autoComplete');

// RUTAS MANUALES
Route::get('{slug}',  'PostController@show');

resources/views/menu/create.blade.php
@extends('layouts.dashboard')
@section('section')
  @if (isset($firstmenus))
    {!!Form::open(['route'=>'firstmenu.store', 'method'=>'POST' , 'class'=>'formulario'])!!}
    @include('menu.forms.fields')
    <div class="form-group text-right">
      {!!Form::submit('Guardar', ['class'=>'btn btn-success'])!!}
    </div>
    {!!Form::close()!!}
  @endif
  {{-- ////////////////////////////////////////////////////////////////// --}}
  @if (isset($firstlist))
    {!!Form::open(['route'=>'secondmenu.store', 'method'=>'POST' , 'class'=>'formulario'])!!}
        <div class="form-group">
          {!!Form::label('Menu')!!}
          {!!Form::select('first_menu_id', $firstlist ,null,['class'=>'form-control','placeholder'=>'Favor escoja un menu'])!!}
        </div>
      @include('menu.forms.fields')
      <div class="form-group text-right">
        {!!Form::submit('Guardar', ['class'=>'btn btn-success'])!!}
      </div>
    {!!Form::close()!!}
  @endif
  {{-- ////////////////////////////////////////////////////////////////// --}}
  @if (isset($secondlist))
    <hr>
    {!!Form::open(['route'=>'thirdmenu.store', 'method'=>'POST' , 'class'=>'formulario'])!!}
        <div class="form-group">
          {!!Form::label('Menu')!!}
          {!!Form::select('second_menu_id', $secondlist ,null,['class'=>'form-control','placeholder'=>'Favor escoja un menu'])!!}
        </div>
      @include('menu.forms.fields')
      <div class="form-group text-right">
        {!!Form::submit('Guardar', ['class'=>'btn btn-success'])!!}
      </div>
    {!!Form::close()!!}
  @endif
@endsection

resources/views/menu/edit.blade.php
@extends('layouts.dashboard')
@section('section')
  @if (isset($firstmenu))
    {!!Form::model($firstmenu ,['route'=>['firstmenu.update' , $firstmenu->id], 'method'=>'PUT' , 'class'=>'formulario'])!!}
    @include('menu.forms.fields')
    <div class="form-group text-right">
      {!!Form::submit('Guardar cambios', ['class'=>'btn btn-success'])!!}
    </div>
    {!!Form::close()!!}
  @endif
  @if (isset($secondmenus))
    {!!Form::model($secondmenus ,['route'=>['secondmenu.update' , $secondmenus->id], 'method'=>'PUT' , 'class'=>'formulario'])!!}
    <div class="form-group">
      {!!Form::label('Menu')!!}
      {!!Form::select('first_menu_id', $firstlist ,null,['class'=>'form-control','placeholder'=>'Favor escoja un menu'])!!}
    </div>
    @include('menu.forms.fields')
    <div class="form-group text-right">
      {!!Form::submit('Guardar cambios', ['class'=>'btn btn-success'])!!}
    </div>
    {!!Form::close()!!}
  @endif
  @if (isset($thirdmenus))
    {!!Form::model($thirdmenus ,['route'=>['thirdmenu.update' , $thirdmenus->id], 'method'=>'PUT' , 'class'=>'formulario'])!!}
    <div class="form-group">
      {!!Form::label('Menu')!!}
      {!!Form::select('second_menu_id', $secondlist ,null,['class'=>'form-control','placeholder'=>'Favor escoja un menu'])!!}
    </div>
    @include('menu.forms.fields')
    <div class="form-group text-right">
      {!!Form::submit('Guardar cambios', ['class'=>'btn btn-success'])!!}
    </div>
    {!!Form::close()!!}
  @endif
@endsection

resources/views/menu/index.blade.php
@extends('layouts.dashboard')
@section('section')
  <table class="table">
    @if (isset($firstmenus))
      <thead>
        <th>Nombre</th>
        <th>Operaciones</th>
      </thead>
      @foreach ($firstmenus as $firstmenu)
        <tbody>
          <td>{{$firstmenu->name}}</td>
          <td>
              {!!Form::open(['route'=>['firstmenu.destroy',$firstmenu->id], 'method'=>'DELETE'])!!}
              <div class="form-group">
                  <a href="{{ route('firstmenu.edit', $firstmenu->id) }}"><i class="btn btn-primary glyphicon glyphicon-pencil"></i></a>
                  {!! Form::button('<span class="glyphicon glyphicon-trash"></span>',
                    [
                        'type' => 'button',
                        'class'=>'btn btn-danger',
                        'onclick' => 'if(confirm("¿Realmente desea eliminar este elemento? ")) {  $(form).submit(); }',
                    ]) !!}
              </div>
              {!!Form::close()!!}
          </td>
        </tbody>
      @endforeach
    @endif

    @if (isset($secondmenus))
      <thead>
        <th>Nombre</th>
        <th>Menu</th>
        <th>Operaciones</th>
      </thead>
      @foreach ($secondmenus as $secondmenu)
        <tbody>
          <td>{{$secondmenu->name}}</td>
          <td>{{$secondmenu->firstmenu->name}}</td>
          <td>
            {!!Form::open(['route'=>['secondmenu.destroy',$secondmenu->id], 'method'=>'DELETE'])!!}
              <a href="{{ route('secondmenu.edit', $secondmenu->id) }}"><i class="btn btn-primary glyphicon glyphicon-pencil"></i></a>
              <div class="form-group">
                  {!! Form::button('<span class="glyphicon glyphicon-trash"></span>',
                  [
                      'type' => 'button',
                      'class'=>'btn btn-danger',
                      'onclick' => 'if(confirm("¿Realmente desea eliminar este elemento? ")) {  $(form).submit(); }',
                  ]) !!}                </div>
            {!!Form::close()!!}
          </td>
        </tbody>
      @endforeach
    @endif

    @if (isset($thirdmenus))
      <thead>
        <th>Nombre</th>
        <th>Submenu</th>
        <th>Menu</th>
        <th>Operaciones</th>
      </thead>
      @foreach ($thirdmenus as $thirdmenu)
        <tbody>
          <td>{{$thirdmenu->name}}</td>
          <td>{{$thirdmenu->secondmenu->name}}</td>
          <td>{{$thirdmenu->secondmenu->firstmenu->name}}</td>
          <td>
            {!!Form::open(['route'=>['thirdmenu.destroy',$thirdmenu->id], 'method'=>'DELETE'])!!}
            <div class="form-group">
              <a href="{{ route('thirdmenu.edit', $thirdmenu->id) }}"><i class="btn btn-primary glyphicon glyphicon-pencil"></i></a>
                {!! Form::button('<span class="glyphicon glyphicon-trash"></span>',
                [
                    'type' => 'button',
                    'class'=>'btn btn-danger',
                    'onclick' => 'if(confirm("¿Realmente desea eliminar este elemento? ")) {  $(form).submit(); }',
                ]) !!}            </div>
            {!!Form::close()!!}
          </td>
        </tbody>
      @endforeach
    @endif
  </table>
@endsection